/**
 * The auth copy view.
 *
 * `packages/auth` renders sign-in, sign-up, recovery and account management for
 * both the calendar and meet, so it needs translations. It does NOT get its own
 * locale directory: 22 of the 23 locales are machine generated by LingoDotDev,
 * whose config scans exactly one path —
 * `buckets.json.include: ["src/calendar/locales/[locale].json"]`.
 *
 * A second directory would need that config extended, a second barrel out of
 * `gen-locales.mjs`, and a new section in `i18n.lock`. Getting any of it wrong
 * presents as translations silently failing to generate on the next CI run, so
 * the copy stays where the pipeline already looks and this is a typed view over
 * the subset the auth components use (ADR 0022).
 */

import { translations, type Language } from '../i18n'

/**
 * The keys the auth components actually reference.
 *
 * Extracted mechanically from the component sources, not by grepping key names.
 * A name-based grep matches 75 keys, of which 20 belong elsewhere:
 * `enterSharePassword` and `sharePasswordLabel` are the share panel's,
 * `setEncryptionPassword` and `passwordOptionalForEncryption` are the backup
 * dialog's, `emailReminder` is an event's. Moving those would leave the calendar
 * rendering key names.
 *
 * Keys used by both surfaces stay in the calendar locale as well — this view
 * selects, it does not remove.
 */
export const authCopyKeys = [
  'account',
  'accountDeleted',
  'accountEmailManagement',
  'analytics',
  'avatarUpdateFailed',
  'avatarUpdated',
  'back',
  'basicInfo',
  'cancel',
  'changeAvatar',
  'changePassword',
  'changePasswordDescription',
  'confirmDeleteAccount',
  'currentPassword',
  'deleteAccount',
  'deleteAccountConfirmDescription',
  'deleteAccountConfirmTitle',
  'deleteAccountFailed',
  'deleteAccountPermanentHelp',
  'deleting',
  'disable2fa',
  'disable2faFailed',
  'editProfileDescription',
  'emailOtpCode',
  'emailUpdatedSuccessfully',
  'enable2faFailed',
  'firstName',
  'invalidOtpCode',
  'lastName',
  'newEmail',
  'newPassword',
  'next',
  'otpCode',
  'password',
  'passwordUpdatedSuccessfully',
  'profile',
  'profileUpdateFailed',
  'profileUpdated',
  'resetPasswordFailed',
  'saveProfile',
  'saving',
  'scanQrFor2fa',
  'sendVerificationCodeFailed',
  'settings',
  'signIn',
  'signOut',
  'signOutHelp',
  'signUp',
  'twoFactorAuthentication',
  'twoFactorAuthenticationDescription',
  'twoFactorEnabledMessage',
  'twoFactorQrCodeAlt',
  'twoFactorSetupVerified',
  'updateEmailFailed',
  'updatePassword',
  'verificationCodeSentEmail',
  'verificationCodeSentNewEmail',
  'verify2faCode',
  'verifyAndUpdateEmail',
] as const

export type AuthCopyKey = (typeof authCopyKeys)[number]
export type AuthCopy = Record<AuthCopyKey, string>

/**
 * The auth strings for one language.
 *
 * Reads through `translations`, which is built as `{...en, ...lang}` — so a key
 * the translator has not reached yet reads as English rather than `undefined`.
 * That fallback is why a newly added key is never user-visible as a raw key name.
 */
export function selectAuthCopy(language: Language): AuthCopy {
  const source = translations[language]
  const copy = {} as AuthCopy
  for (const key of authCopyKeys) {
    // Via unknown: the locale also holds array values (weekdays), so it is not
    // assignable to Record<string, string> directly. Every key in authCopyKeys
    // is a string, which the test suite asserts against the real locale files.
    copy[key] = (source as unknown as Record<string, string>)[key]
  }
  return copy
}

export type { Language }
