/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `AtprotoShareBurnRead` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'
import type * as $Enums from '../enums'
import type * as Prisma from '../internal/prismaNamespace'

/**
 * Model AtprotoShareBurnRead
 *
 */
export type AtprotoShareBurnReadModel =
  runtime.Types.Result.DefaultSelection<Prisma.$AtprotoShareBurnReadPayload>

export type AggregateAtprotoShareBurnRead = {
  _count: AtprotoShareBurnReadCountAggregateOutputType | null
  _min: AtprotoShareBurnReadMinAggregateOutputType | null
  _max: AtprotoShareBurnReadMaxAggregateOutputType | null
}

export type AtprotoShareBurnReadMinAggregateOutputType = {
  handle: string | null
  ownerDid: string | null
  shareId: string | null
  burnedAt: Date | null
  pdsDeleteSynced: boolean | null
}

export type AtprotoShareBurnReadMaxAggregateOutputType = {
  handle: string | null
  ownerDid: string | null
  shareId: string | null
  burnedAt: Date | null
  pdsDeleteSynced: boolean | null
}

export type AtprotoShareBurnReadCountAggregateOutputType = {
  handle: number
  ownerDid: number
  shareId: number
  burnedAt: number
  pdsDeleteSynced: number
  _all: number
}

export type AtprotoShareBurnReadMinAggregateInputType = {
  handle?: true
  ownerDid?: true
  shareId?: true
  burnedAt?: true
  pdsDeleteSynced?: true
}

export type AtprotoShareBurnReadMaxAggregateInputType = {
  handle?: true
  ownerDid?: true
  shareId?: true
  burnedAt?: true
  pdsDeleteSynced?: true
}

export type AtprotoShareBurnReadCountAggregateInputType = {
  handle?: true
  ownerDid?: true
  shareId?: true
  burnedAt?: true
  pdsDeleteSynced?: true
  _all?: true
}

export type AtprotoShareBurnReadAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which AtprotoShareBurnRead to aggregate.
   */
  where?: Prisma.AtprotoShareBurnReadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of AtprotoShareBurnReads to fetch.
   */
  orderBy?:
    | Prisma.AtprotoShareBurnReadOrderByWithRelationInput
    | Prisma.AtprotoShareBurnReadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.AtprotoShareBurnReadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` AtprotoShareBurnReads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` AtprotoShareBurnReads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned AtprotoShareBurnReads
   **/
  _count?: true | AtprotoShareBurnReadCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: AtprotoShareBurnReadMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: AtprotoShareBurnReadMaxAggregateInputType
}

export type GetAtprotoShareBurnReadAggregateType<
  T extends AtprotoShareBurnReadAggregateArgs,
> = {
  [P in keyof T & keyof AggregateAtprotoShareBurnRead]: P extends
    | '_count'
    | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAtprotoShareBurnRead[P]>
    : Prisma.GetScalarType<T[P], AggregateAtprotoShareBurnRead[P]>
}

export type AtprotoShareBurnReadGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.AtprotoShareBurnReadWhereInput
  orderBy?:
    | Prisma.AtprotoShareBurnReadOrderByWithAggregationInput
    | Prisma.AtprotoShareBurnReadOrderByWithAggregationInput[]
  by:
    | Prisma.AtprotoShareBurnReadScalarFieldEnum[]
    | Prisma.AtprotoShareBurnReadScalarFieldEnum
  having?: Prisma.AtprotoShareBurnReadScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AtprotoShareBurnReadCountAggregateInputType | true
  _min?: AtprotoShareBurnReadMinAggregateInputType
  _max?: AtprotoShareBurnReadMaxAggregateInputType
}

export type AtprotoShareBurnReadGroupByOutputType = {
  handle: string
  ownerDid: string | null
  shareId: string
  burnedAt: Date
  pdsDeleteSynced: boolean
  _count: AtprotoShareBurnReadCountAggregateOutputType | null
  _min: AtprotoShareBurnReadMinAggregateOutputType | null
  _max: AtprotoShareBurnReadMaxAggregateOutputType | null
}

export type GetAtprotoShareBurnReadGroupByPayload<
  T extends AtprotoShareBurnReadGroupByArgs,
> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AtprotoShareBurnReadGroupByOutputType, T['by']> & {
      [P in keyof T &
        keyof AtprotoShareBurnReadGroupByOutputType]: P extends '_count'
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], AtprotoShareBurnReadGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], AtprotoShareBurnReadGroupByOutputType[P]>
    }
  >
>

export type AtprotoShareBurnReadWhereInput = {
  AND?:
    | Prisma.AtprotoShareBurnReadWhereInput
    | Prisma.AtprotoShareBurnReadWhereInput[]
  OR?: Prisma.AtprotoShareBurnReadWhereInput[]
  NOT?:
    | Prisma.AtprotoShareBurnReadWhereInput
    | Prisma.AtprotoShareBurnReadWhereInput[]
  handle?: Prisma.StringFilter<'AtprotoShareBurnRead'> | string
  ownerDid?: Prisma.StringNullableFilter<'AtprotoShareBurnRead'> | string | null
  shareId?: Prisma.StringFilter<'AtprotoShareBurnRead'> | string
  burnedAt?: Prisma.DateTimeFilter<'AtprotoShareBurnRead'> | Date | string
  pdsDeleteSynced?: Prisma.BoolFilter<'AtprotoShareBurnRead'> | boolean
}

export type AtprotoShareBurnReadOrderByWithRelationInput = {
  handle?: Prisma.SortOrder
  ownerDid?: Prisma.SortOrderInput | Prisma.SortOrder
  shareId?: Prisma.SortOrder
  burnedAt?: Prisma.SortOrder
  pdsDeleteSynced?: Prisma.SortOrder
}

export type AtprotoShareBurnReadWhereUniqueInput = Prisma.AtLeast<
  {
    shareId_handle?: Prisma.AtprotoShareBurnReadShareIdHandleCompoundUniqueInput
    AND?:
      | Prisma.AtprotoShareBurnReadWhereInput
      | Prisma.AtprotoShareBurnReadWhereInput[]
    OR?: Prisma.AtprotoShareBurnReadWhereInput[]
    NOT?:
      | Prisma.AtprotoShareBurnReadWhereInput
      | Prisma.AtprotoShareBurnReadWhereInput[]
    handle?: Prisma.StringFilter<'AtprotoShareBurnRead'> | string
    ownerDid?:
      | Prisma.StringNullableFilter<'AtprotoShareBurnRead'>
      | string
      | null
    shareId?: Prisma.StringFilter<'AtprotoShareBurnRead'> | string
    burnedAt?: Prisma.DateTimeFilter<'AtprotoShareBurnRead'> | Date | string
    pdsDeleteSynced?: Prisma.BoolFilter<'AtprotoShareBurnRead'> | boolean
  },
  'shareId_handle'
>

export type AtprotoShareBurnReadOrderByWithAggregationInput = {
  handle?: Prisma.SortOrder
  ownerDid?: Prisma.SortOrderInput | Prisma.SortOrder
  shareId?: Prisma.SortOrder
  burnedAt?: Prisma.SortOrder
  pdsDeleteSynced?: Prisma.SortOrder
  _count?: Prisma.AtprotoShareBurnReadCountOrderByAggregateInput
  _max?: Prisma.AtprotoShareBurnReadMaxOrderByAggregateInput
  _min?: Prisma.AtprotoShareBurnReadMinOrderByAggregateInput
}

export type AtprotoShareBurnReadScalarWhereWithAggregatesInput = {
  AND?:
    | Prisma.AtprotoShareBurnReadScalarWhereWithAggregatesInput
    | Prisma.AtprotoShareBurnReadScalarWhereWithAggregatesInput[]
  OR?: Prisma.AtprotoShareBurnReadScalarWhereWithAggregatesInput[]
  NOT?:
    | Prisma.AtprotoShareBurnReadScalarWhereWithAggregatesInput
    | Prisma.AtprotoShareBurnReadScalarWhereWithAggregatesInput[]
  handle?: Prisma.StringWithAggregatesFilter<'AtprotoShareBurnRead'> | string
  ownerDid?:
    | Prisma.StringNullableWithAggregatesFilter<'AtprotoShareBurnRead'>
    | string
    | null
  shareId?: Prisma.StringWithAggregatesFilter<'AtprotoShareBurnRead'> | string
  burnedAt?:
    | Prisma.DateTimeWithAggregatesFilter<'AtprotoShareBurnRead'>
    | Date
    | string
  pdsDeleteSynced?:
    | Prisma.BoolWithAggregatesFilter<'AtprotoShareBurnRead'>
    | boolean
}

export type AtprotoShareBurnReadCreateInput = {
  handle: string
  ownerDid?: string | null
  shareId: string
  burnedAt?: Date | string
  pdsDeleteSynced?: boolean
}

export type AtprotoShareBurnReadUncheckedCreateInput = {
  handle: string
  ownerDid?: string | null
  shareId: string
  burnedAt?: Date | string
  pdsDeleteSynced?: boolean
}

export type AtprotoShareBurnReadUpdateInput = {
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  ownerDid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shareId?: Prisma.StringFieldUpdateOperationsInput | string
  burnedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pdsDeleteSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type AtprotoShareBurnReadUncheckedUpdateInput = {
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  ownerDid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shareId?: Prisma.StringFieldUpdateOperationsInput | string
  burnedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pdsDeleteSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type AtprotoShareBurnReadCreateManyInput = {
  handle: string
  ownerDid?: string | null
  shareId: string
  burnedAt?: Date | string
  pdsDeleteSynced?: boolean
}

export type AtprotoShareBurnReadUpdateManyMutationInput = {
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  ownerDid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shareId?: Prisma.StringFieldUpdateOperationsInput | string
  burnedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pdsDeleteSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type AtprotoShareBurnReadUncheckedUpdateManyInput = {
  handle?: Prisma.StringFieldUpdateOperationsInput | string
  ownerDid?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shareId?: Prisma.StringFieldUpdateOperationsInput | string
  burnedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  pdsDeleteSynced?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type AtprotoShareBurnReadShareIdHandleCompoundUniqueInput = {
  shareId: string
  handle: string
}

export type AtprotoShareBurnReadCountOrderByAggregateInput = {
  handle?: Prisma.SortOrder
  ownerDid?: Prisma.SortOrder
  shareId?: Prisma.SortOrder
  burnedAt?: Prisma.SortOrder
  pdsDeleteSynced?: Prisma.SortOrder
}

export type AtprotoShareBurnReadMaxOrderByAggregateInput = {
  handle?: Prisma.SortOrder
  ownerDid?: Prisma.SortOrder
  shareId?: Prisma.SortOrder
  burnedAt?: Prisma.SortOrder
  pdsDeleteSynced?: Prisma.SortOrder
}

export type AtprotoShareBurnReadMinOrderByAggregateInput = {
  handle?: Prisma.SortOrder
  ownerDid?: Prisma.SortOrder
  shareId?: Prisma.SortOrder
  burnedAt?: Prisma.SortOrder
  pdsDeleteSynced?: Prisma.SortOrder
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type AtprotoShareBurnReadSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    handle?: boolean
    ownerDid?: boolean
    shareId?: boolean
    burnedAt?: boolean
    pdsDeleteSynced?: boolean
  },
  ExtArgs['result']['atprotoShareBurnRead']
>

export type AtprotoShareBurnReadSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    handle?: boolean
    ownerDid?: boolean
    shareId?: boolean
    burnedAt?: boolean
    pdsDeleteSynced?: boolean
  },
  ExtArgs['result']['atprotoShareBurnRead']
>

export type AtprotoShareBurnReadSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    handle?: boolean
    ownerDid?: boolean
    shareId?: boolean
    burnedAt?: boolean
    pdsDeleteSynced?: boolean
  },
  ExtArgs['result']['atprotoShareBurnRead']
>

export type AtprotoShareBurnReadSelectScalar = {
  handle?: boolean
  ownerDid?: boolean
  shareId?: boolean
  burnedAt?: boolean
  pdsDeleteSynced?: boolean
}

export type AtprotoShareBurnReadOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<
  'handle' | 'ownerDid' | 'shareId' | 'burnedAt' | 'pdsDeleteSynced',
  ExtArgs['result']['atprotoShareBurnRead']
>

export type $AtprotoShareBurnReadPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'AtprotoShareBurnRead'
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      handle: string
      ownerDid: string | null
      shareId: string
      burnedAt: Date
      pdsDeleteSynced: boolean
    },
    ExtArgs['result']['atprotoShareBurnRead']
  >
  composites: {}
}

export type AtprotoShareBurnReadGetPayload<
  S extends boolean | null | undefined | AtprotoShareBurnReadDefaultArgs,
> = runtime.Types.Result.GetResult<Prisma.$AtprotoShareBurnReadPayload, S>

export type AtprotoShareBurnReadCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = Omit<
  AtprotoShareBurnReadFindManyArgs,
  'select' | 'include' | 'distinct' | 'omit'
> & {
  select?: AtprotoShareBurnReadCountAggregateInputType | true
}

export interface AtprotoShareBurnReadDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: {
    types: Prisma.TypeMap<ExtArgs>['model']['AtprotoShareBurnRead']
    meta: { name: 'AtprotoShareBurnRead' }
  }
  /**
   * Find zero or one AtprotoShareBurnRead that matches the filter.
   * @param {AtprotoShareBurnReadFindUniqueArgs} args - Arguments to find a AtprotoShareBurnRead
   * @example
   * // Get one AtprotoShareBurnRead
   * const atprotoShareBurnRead = await prisma.atprotoShareBurnRead.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AtprotoShareBurnReadFindUniqueArgs>(
    args: Prisma.SelectSubset<T, AtprotoShareBurnReadFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__AtprotoShareBurnReadClient<
    runtime.Types.Result.GetResult<
      Prisma.$AtprotoShareBurnReadPayload<ExtArgs>,
      T,
      'findUnique',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one AtprotoShareBurnRead that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AtprotoShareBurnReadFindUniqueOrThrowArgs} args - Arguments to find a AtprotoShareBurnRead
   * @example
   * // Get one AtprotoShareBurnRead
   * const atprotoShareBurnRead = await prisma.atprotoShareBurnRead.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AtprotoShareBurnReadFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<
      T,
      AtprotoShareBurnReadFindUniqueOrThrowArgs<ExtArgs>
    >,
  ): Prisma.Prisma__AtprotoShareBurnReadClient<
    runtime.Types.Result.GetResult<
      Prisma.$AtprotoShareBurnReadPayload<ExtArgs>,
      T,
      'findUniqueOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first AtprotoShareBurnRead that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AtprotoShareBurnReadFindFirstArgs} args - Arguments to find a AtprotoShareBurnRead
   * @example
   * // Get one AtprotoShareBurnRead
   * const atprotoShareBurnRead = await prisma.atprotoShareBurnRead.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AtprotoShareBurnReadFindFirstArgs>(
    args?: Prisma.SelectSubset<T, AtprotoShareBurnReadFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__AtprotoShareBurnReadClient<
    runtime.Types.Result.GetResult<
      Prisma.$AtprotoShareBurnReadPayload<ExtArgs>,
      T,
      'findFirst',
      GlobalOmitOptions
    > | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first AtprotoShareBurnRead that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AtprotoShareBurnReadFindFirstOrThrowArgs} args - Arguments to find a AtprotoShareBurnRead
   * @example
   * // Get one AtprotoShareBurnRead
   * const atprotoShareBurnRead = await prisma.atprotoShareBurnRead.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AtprotoShareBurnReadFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<
      T,
      AtprotoShareBurnReadFindFirstOrThrowArgs<ExtArgs>
    >,
  ): Prisma.Prisma__AtprotoShareBurnReadClient<
    runtime.Types.Result.GetResult<
      Prisma.$AtprotoShareBurnReadPayload<ExtArgs>,
      T,
      'findFirstOrThrow',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more AtprotoShareBurnReads that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AtprotoShareBurnReadFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AtprotoShareBurnReads
   * const atprotoShareBurnReads = await prisma.atprotoShareBurnRead.findMany()
   *
   * // Get first 10 AtprotoShareBurnReads
   * const atprotoShareBurnReads = await prisma.atprotoShareBurnRead.findMany({ take: 10 })
   *
   * // Only select the `handle`
   * const atprotoShareBurnReadWithHandleOnly = await prisma.atprotoShareBurnRead.findMany({ select: { handle: true } })
   *
   */
  findMany<T extends AtprotoShareBurnReadFindManyArgs>(
    args?: Prisma.SelectSubset<T, AtprotoShareBurnReadFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$AtprotoShareBurnReadPayload<ExtArgs>,
      T,
      'findMany',
      GlobalOmitOptions
    >
  >

  /**
   * Create a AtprotoShareBurnRead.
   * @param {AtprotoShareBurnReadCreateArgs} args - Arguments to create a AtprotoShareBurnRead.
   * @example
   * // Create one AtprotoShareBurnRead
   * const AtprotoShareBurnRead = await prisma.atprotoShareBurnRead.create({
   *   data: {
   *     // ... data to create a AtprotoShareBurnRead
   *   }
   * })
   *
   */
  create<T extends AtprotoShareBurnReadCreateArgs>(
    args: Prisma.SelectSubset<T, AtprotoShareBurnReadCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__AtprotoShareBurnReadClient<
    runtime.Types.Result.GetResult<
      Prisma.$AtprotoShareBurnReadPayload<ExtArgs>,
      T,
      'create',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many AtprotoShareBurnReads.
   * @param {AtprotoShareBurnReadCreateManyArgs} args - Arguments to create many AtprotoShareBurnReads.
   * @example
   * // Create many AtprotoShareBurnReads
   * const atprotoShareBurnRead = await prisma.atprotoShareBurnRead.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends AtprotoShareBurnReadCreateManyArgs>(
    args?: Prisma.SelectSubset<T, AtprotoShareBurnReadCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AtprotoShareBurnReads and returns the data saved in the database.
   * @param {AtprotoShareBurnReadCreateManyAndReturnArgs} args - Arguments to create many AtprotoShareBurnReads.
   * @example
   * // Create many AtprotoShareBurnReads
   * const atprotoShareBurnRead = await prisma.atprotoShareBurnRead.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many AtprotoShareBurnReads and only return the `handle`
   * const atprotoShareBurnReadWithHandleOnly = await prisma.atprotoShareBurnRead.createManyAndReturn({
   *   select: { handle: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends AtprotoShareBurnReadCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<
      T,
      AtprotoShareBurnReadCreateManyAndReturnArgs<ExtArgs>
    >,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$AtprotoShareBurnReadPayload<ExtArgs>,
      T,
      'createManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Delete a AtprotoShareBurnRead.
   * @param {AtprotoShareBurnReadDeleteArgs} args - Arguments to delete one AtprotoShareBurnRead.
   * @example
   * // Delete one AtprotoShareBurnRead
   * const AtprotoShareBurnRead = await prisma.atprotoShareBurnRead.delete({
   *   where: {
   *     // ... filter to delete one AtprotoShareBurnRead
   *   }
   * })
   *
   */
  delete<T extends AtprotoShareBurnReadDeleteArgs>(
    args: Prisma.SelectSubset<T, AtprotoShareBurnReadDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__AtprotoShareBurnReadClient<
    runtime.Types.Result.GetResult<
      Prisma.$AtprotoShareBurnReadPayload<ExtArgs>,
      T,
      'delete',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one AtprotoShareBurnRead.
   * @param {AtprotoShareBurnReadUpdateArgs} args - Arguments to update one AtprotoShareBurnRead.
   * @example
   * // Update one AtprotoShareBurnRead
   * const atprotoShareBurnRead = await prisma.atprotoShareBurnRead.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends AtprotoShareBurnReadUpdateArgs>(
    args: Prisma.SelectSubset<T, AtprotoShareBurnReadUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__AtprotoShareBurnReadClient<
    runtime.Types.Result.GetResult<
      Prisma.$AtprotoShareBurnReadPayload<ExtArgs>,
      T,
      'update',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more AtprotoShareBurnReads.
   * @param {AtprotoShareBurnReadDeleteManyArgs} args - Arguments to filter AtprotoShareBurnReads to delete.
   * @example
   * // Delete a few AtprotoShareBurnReads
   * const { count } = await prisma.atprotoShareBurnRead.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends AtprotoShareBurnReadDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, AtprotoShareBurnReadDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AtprotoShareBurnReads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AtprotoShareBurnReadUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AtprotoShareBurnReads
   * const atprotoShareBurnRead = await prisma.atprotoShareBurnRead.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends AtprotoShareBurnReadUpdateManyArgs>(
    args: Prisma.SelectSubset<T, AtprotoShareBurnReadUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AtprotoShareBurnReads and returns the data updated in the database.
   * @param {AtprotoShareBurnReadUpdateManyAndReturnArgs} args - Arguments to update many AtprotoShareBurnReads.
   * @example
   * // Update many AtprotoShareBurnReads
   * const atprotoShareBurnRead = await prisma.atprotoShareBurnRead.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more AtprotoShareBurnReads and only return the `handle`
   * const atprotoShareBurnReadWithHandleOnly = await prisma.atprotoShareBurnRead.updateManyAndReturn({
   *   select: { handle: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends AtprotoShareBurnReadUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<
      T,
      AtprotoShareBurnReadUpdateManyAndReturnArgs<ExtArgs>
    >,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<
      Prisma.$AtprotoShareBurnReadPayload<ExtArgs>,
      T,
      'updateManyAndReturn',
      GlobalOmitOptions
    >
  >

  /**
   * Create or update one AtprotoShareBurnRead.
   * @param {AtprotoShareBurnReadUpsertArgs} args - Arguments to update or create a AtprotoShareBurnRead.
   * @example
   * // Update or create a AtprotoShareBurnRead
   * const atprotoShareBurnRead = await prisma.atprotoShareBurnRead.upsert({
   *   create: {
   *     // ... data to create a AtprotoShareBurnRead
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AtprotoShareBurnRead we want to update
   *   }
   * })
   */
  upsert<T extends AtprotoShareBurnReadUpsertArgs>(
    args: Prisma.SelectSubset<T, AtprotoShareBurnReadUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__AtprotoShareBurnReadClient<
    runtime.Types.Result.GetResult<
      Prisma.$AtprotoShareBurnReadPayload<ExtArgs>,
      T,
      'upsert',
      GlobalOmitOptions
    >,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of AtprotoShareBurnReads.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AtprotoShareBurnReadCountArgs} args - Arguments to filter AtprotoShareBurnReads to count.
   * @example
   * // Count the number of AtprotoShareBurnReads
   * const count = await prisma.atprotoShareBurnRead.count({
   *   where: {
   *     // ... the filter for the AtprotoShareBurnReads we want to count
   *   }
   * })
   **/
  count<T extends AtprotoShareBurnReadCountArgs>(
    args?: Prisma.Subset<T, AtprotoShareBurnReadCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<
            T['select'],
            AtprotoShareBurnReadCountAggregateOutputType
          >
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AtprotoShareBurnRead.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AtprotoShareBurnReadAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends AtprotoShareBurnReadAggregateArgs>(
    args: Prisma.Subset<T, AtprotoShareBurnReadAggregateArgs>,
  ): Prisma.PrismaPromise<GetAtprotoShareBurnReadAggregateType<T>>

  /**
   * Group by AtprotoShareBurnRead.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AtprotoShareBurnReadGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends AtprotoShareBurnReadGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AtprotoShareBurnReadGroupByArgs['orderBy'] }
      : { orderBy?: AtprotoShareBurnReadGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<
      Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>
    >,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [
                    Error,
                    'Field ',
                    P,
                    ` in "having" needs to be provided in "by"`,
                  ]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<
      T,
      AtprotoShareBurnReadGroupByArgs,
      OrderByArg
    > &
      InputErrors,
  ): {} extends InputErrors
    ? GetAtprotoShareBurnReadGroupByPayload<T>
    : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the AtprotoShareBurnRead model
   */
  readonly fields: AtprotoShareBurnReadFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for AtprotoShareBurnRead.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AtprotoShareBurnReadClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?:
      | ((value: T) => TResult1 | PromiseLike<TResult1>)
      | undefined
      | null,
    onrejected?:
      | ((reason: any) => TResult2 | PromiseLike<TResult2>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?:
      | ((reason: any) => TResult | PromiseLike<TResult>)
      | undefined
      | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(
    onfinally?: (() => void) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the AtprotoShareBurnRead model
 */
export interface AtprotoShareBurnReadFieldRefs {
  readonly handle: Prisma.FieldRef<'AtprotoShareBurnRead', 'String'>
  readonly ownerDid: Prisma.FieldRef<'AtprotoShareBurnRead', 'String'>
  readonly shareId: Prisma.FieldRef<'AtprotoShareBurnRead', 'String'>
  readonly burnedAt: Prisma.FieldRef<'AtprotoShareBurnRead', 'DateTime'>
  readonly pdsDeleteSynced: Prisma.FieldRef<'AtprotoShareBurnRead', 'Boolean'>
}

// Custom InputTypes
/**
 * AtprotoShareBurnRead findUnique
 */
export type AtprotoShareBurnReadFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AtprotoShareBurnRead
   */
  select?: Prisma.AtprotoShareBurnReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AtprotoShareBurnRead
   */
  omit?: Prisma.AtprotoShareBurnReadOmit<ExtArgs> | null
  /**
   * Filter, which AtprotoShareBurnRead to fetch.
   */
  where: Prisma.AtprotoShareBurnReadWhereUniqueInput
}

/**
 * AtprotoShareBurnRead findUniqueOrThrow
 */
export type AtprotoShareBurnReadFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AtprotoShareBurnRead
   */
  select?: Prisma.AtprotoShareBurnReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AtprotoShareBurnRead
   */
  omit?: Prisma.AtprotoShareBurnReadOmit<ExtArgs> | null
  /**
   * Filter, which AtprotoShareBurnRead to fetch.
   */
  where: Prisma.AtprotoShareBurnReadWhereUniqueInput
}

/**
 * AtprotoShareBurnRead findFirst
 */
export type AtprotoShareBurnReadFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AtprotoShareBurnRead
   */
  select?: Prisma.AtprotoShareBurnReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AtprotoShareBurnRead
   */
  omit?: Prisma.AtprotoShareBurnReadOmit<ExtArgs> | null
  /**
   * Filter, which AtprotoShareBurnRead to fetch.
   */
  where?: Prisma.AtprotoShareBurnReadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of AtprotoShareBurnReads to fetch.
   */
  orderBy?:
    | Prisma.AtprotoShareBurnReadOrderByWithRelationInput
    | Prisma.AtprotoShareBurnReadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for AtprotoShareBurnReads.
   */
  cursor?: Prisma.AtprotoShareBurnReadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` AtprotoShareBurnReads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` AtprotoShareBurnReads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of AtprotoShareBurnReads.
   */
  distinct?:
    | Prisma.AtprotoShareBurnReadScalarFieldEnum
    | Prisma.AtprotoShareBurnReadScalarFieldEnum[]
}

/**
 * AtprotoShareBurnRead findFirstOrThrow
 */
export type AtprotoShareBurnReadFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AtprotoShareBurnRead
   */
  select?: Prisma.AtprotoShareBurnReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AtprotoShareBurnRead
   */
  omit?: Prisma.AtprotoShareBurnReadOmit<ExtArgs> | null
  /**
   * Filter, which AtprotoShareBurnRead to fetch.
   */
  where?: Prisma.AtprotoShareBurnReadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of AtprotoShareBurnReads to fetch.
   */
  orderBy?:
    | Prisma.AtprotoShareBurnReadOrderByWithRelationInput
    | Prisma.AtprotoShareBurnReadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for AtprotoShareBurnReads.
   */
  cursor?: Prisma.AtprotoShareBurnReadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` AtprotoShareBurnReads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` AtprotoShareBurnReads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of AtprotoShareBurnReads.
   */
  distinct?:
    | Prisma.AtprotoShareBurnReadScalarFieldEnum
    | Prisma.AtprotoShareBurnReadScalarFieldEnum[]
}

/**
 * AtprotoShareBurnRead findMany
 */
export type AtprotoShareBurnReadFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AtprotoShareBurnRead
   */
  select?: Prisma.AtprotoShareBurnReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AtprotoShareBurnRead
   */
  omit?: Prisma.AtprotoShareBurnReadOmit<ExtArgs> | null
  /**
   * Filter, which AtprotoShareBurnReads to fetch.
   */
  where?: Prisma.AtprotoShareBurnReadWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of AtprotoShareBurnReads to fetch.
   */
  orderBy?:
    | Prisma.AtprotoShareBurnReadOrderByWithRelationInput
    | Prisma.AtprotoShareBurnReadOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing AtprotoShareBurnReads.
   */
  cursor?: Prisma.AtprotoShareBurnReadWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` AtprotoShareBurnReads from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` AtprotoShareBurnReads.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of AtprotoShareBurnReads.
   */
  distinct?:
    | Prisma.AtprotoShareBurnReadScalarFieldEnum
    | Prisma.AtprotoShareBurnReadScalarFieldEnum[]
}

/**
 * AtprotoShareBurnRead create
 */
export type AtprotoShareBurnReadCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AtprotoShareBurnRead
   */
  select?: Prisma.AtprotoShareBurnReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AtprotoShareBurnRead
   */
  omit?: Prisma.AtprotoShareBurnReadOmit<ExtArgs> | null
  /**
   * The data needed to create a AtprotoShareBurnRead.
   */
  data: Prisma.XOR<
    Prisma.AtprotoShareBurnReadCreateInput,
    Prisma.AtprotoShareBurnReadUncheckedCreateInput
  >
}

/**
 * AtprotoShareBurnRead createMany
 */
export type AtprotoShareBurnReadCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many AtprotoShareBurnReads.
   */
  data:
    | Prisma.AtprotoShareBurnReadCreateManyInput
    | Prisma.AtprotoShareBurnReadCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AtprotoShareBurnRead createManyAndReturn
 */
export type AtprotoShareBurnReadCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AtprotoShareBurnRead
   */
  select?: Prisma.AtprotoShareBurnReadSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AtprotoShareBurnRead
   */
  omit?: Prisma.AtprotoShareBurnReadOmit<ExtArgs> | null
  /**
   * The data used to create many AtprotoShareBurnReads.
   */
  data:
    | Prisma.AtprotoShareBurnReadCreateManyInput
    | Prisma.AtprotoShareBurnReadCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AtprotoShareBurnRead update
 */
export type AtprotoShareBurnReadUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AtprotoShareBurnRead
   */
  select?: Prisma.AtprotoShareBurnReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AtprotoShareBurnRead
   */
  omit?: Prisma.AtprotoShareBurnReadOmit<ExtArgs> | null
  /**
   * The data needed to update a AtprotoShareBurnRead.
   */
  data: Prisma.XOR<
    Prisma.AtprotoShareBurnReadUpdateInput,
    Prisma.AtprotoShareBurnReadUncheckedUpdateInput
  >
  /**
   * Choose, which AtprotoShareBurnRead to update.
   */
  where: Prisma.AtprotoShareBurnReadWhereUniqueInput
}

/**
 * AtprotoShareBurnRead updateMany
 */
export type AtprotoShareBurnReadUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update AtprotoShareBurnReads.
   */
  data: Prisma.XOR<
    Prisma.AtprotoShareBurnReadUpdateManyMutationInput,
    Prisma.AtprotoShareBurnReadUncheckedUpdateManyInput
  >
  /**
   * Filter which AtprotoShareBurnReads to update
   */
  where?: Prisma.AtprotoShareBurnReadWhereInput
  /**
   * Limit how many AtprotoShareBurnReads to update.
   */
  limit?: number
}

/**
 * AtprotoShareBurnRead updateManyAndReturn
 */
export type AtprotoShareBurnReadUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AtprotoShareBurnRead
   */
  select?: Prisma.AtprotoShareBurnReadSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AtprotoShareBurnRead
   */
  omit?: Prisma.AtprotoShareBurnReadOmit<ExtArgs> | null
  /**
   * The data used to update AtprotoShareBurnReads.
   */
  data: Prisma.XOR<
    Prisma.AtprotoShareBurnReadUpdateManyMutationInput,
    Prisma.AtprotoShareBurnReadUncheckedUpdateManyInput
  >
  /**
   * Filter which AtprotoShareBurnReads to update
   */
  where?: Prisma.AtprotoShareBurnReadWhereInput
  /**
   * Limit how many AtprotoShareBurnReads to update.
   */
  limit?: number
}

/**
 * AtprotoShareBurnRead upsert
 */
export type AtprotoShareBurnReadUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AtprotoShareBurnRead
   */
  select?: Prisma.AtprotoShareBurnReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AtprotoShareBurnRead
   */
  omit?: Prisma.AtprotoShareBurnReadOmit<ExtArgs> | null
  /**
   * The filter to search for the AtprotoShareBurnRead to update in case it exists.
   */
  where: Prisma.AtprotoShareBurnReadWhereUniqueInput
  /**
   * In case the AtprotoShareBurnRead found by the `where` argument doesn't exist, create a new AtprotoShareBurnRead with this data.
   */
  create: Prisma.XOR<
    Prisma.AtprotoShareBurnReadCreateInput,
    Prisma.AtprotoShareBurnReadUncheckedCreateInput
  >
  /**
   * In case the AtprotoShareBurnRead was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<
    Prisma.AtprotoShareBurnReadUpdateInput,
    Prisma.AtprotoShareBurnReadUncheckedUpdateInput
  >
}

/**
 * AtprotoShareBurnRead delete
 */
export type AtprotoShareBurnReadDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AtprotoShareBurnRead
   */
  select?: Prisma.AtprotoShareBurnReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AtprotoShareBurnRead
   */
  omit?: Prisma.AtprotoShareBurnReadOmit<ExtArgs> | null
  /**
   * Filter which AtprotoShareBurnRead to delete.
   */
  where: Prisma.AtprotoShareBurnReadWhereUniqueInput
}

/**
 * AtprotoShareBurnRead deleteMany
 */
export type AtprotoShareBurnReadDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which AtprotoShareBurnReads to delete
   */
  where?: Prisma.AtprotoShareBurnReadWhereInput
  /**
   * Limit how many AtprotoShareBurnReads to delete.
   */
  limit?: number
}

/**
 * AtprotoShareBurnRead without action
 */
export type AtprotoShareBurnReadDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs =
    runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the AtprotoShareBurnRead
   */
  select?: Prisma.AtprotoShareBurnReadSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AtprotoShareBurnRead
   */
  omit?: Prisma.AtprotoShareBurnReadOmit<ExtArgs> | null
}
