packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  less: false
  msw: false
  nx: true
  sharp: false
  unrs-resolver: false
onlyBuiltDependencies:
  - sharp
  - esbuild
  - nx
