packages:
  - 'apps/*'
  - 'packages/*'
supportedArchitectures:
  os:
    - current
  cpu:
    - current
    - wasm32
allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  less: false
  msw: false
  sharp: false
  unrs-resolver: false
onlyBuiltDependencies:
  - sharp
  - esbuild
minimumReleaseAgeExclude:
  - '@better-auth/infra@0.4.3'
