import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { authCopyKeys, selectAuthCopy } from '@zntr/i18n/auth'

/**
 * The auth copy view.
 *
 * `packages/auth` renders account management for both apps, so it needs the
 * translations — but 22 of the 23 locales are machine generated by LingoDotDev,
 * whose config scans exactly one directory
 * (`buckets.json.include: ["src/calendar/locales/[locale].json"]`).
 *
 * So the copy stays in those files and this is a typed view over the subset the
 * auth components use (ADR 0022). A separate locale directory would need that
 * config extended, a second barrel from gen-locales, and a new section in
 * i18n.lock — and getting it wrong shows up as translations silently failing to
 * generate on the next CI run.
 */
const ROOT = resolve(__dirname, '../..')

const readLocale = (lang: string) =>
  JSON.parse(
    readFileSync(
      resolve(ROOT, `packages/i18n/src/calendar/locales/${lang}.json`),
      'utf8',
    ),
  ) as Record<string, string>

describe('authCopyKeys', () => {
  it('covers every key the auth components reference', () => {
    // Extracted mechanically from the components rather than by grepping key
    // names: /password/ also matches enterSharePassword and
    // setEncryptionPassword, and taking those would leave the calendar's share
    // panel and backup dialog rendering key names.
    expect(authCopyKeys.length).toBeGreaterThan(50)
  })

  it('excludes the keys that only incidentally look like auth', () => {
    // These belong to the share panel, the backup dialog and event reminders.
    for (const foreign of [
      'enterSharePassword',
      'setEncryptionPassword',
      'sharePasswordLabel',
      'emailReminder',
      'passwordOptionalForEncryption',
      'shareSignInRequiredTitle',
    ]) {
      expect(authCopyKeys).not.toContain(foreign)
    }
  })

  it('has no duplicates', () => {
    expect(new Set(authCopyKeys).size).toBe(authCopyKeys.length)
  })

  it('every key exists in the English source', () => {
    // en is the LingoDotDev source locale; a key absent here can never be
    // translated, and would render as undefined in all 23 languages.
    const en = readLocale('en')
    const missing = authCopyKeys.filter((k) => !(k in en))
    expect(missing).toEqual([])
  })
})

describe('selectAuthCopy', () => {
  it('returns the auth subset for a language', () => {
    const copy = selectAuthCopy('en')
    expect(copy.signIn).toBe('Sign In')
    expect(copy.deleteAccount).toBe('Delete account')
  })

  it('returns only the auth keys, not the whole calendar locale', () => {
    // The point of the view is that packages/auth cannot accidentally depend on
    // a calendar-only string, which would then be missing when meet renders the
    // same component.
    const copy = selectAuthCopy('en')
    expect(Object.keys(copy).sort()).toEqual([...authCopyKeys].sort())
    expect('enterSharePassword' in copy).toBe(false)
  })

  it('falls back to English for a language missing a translation', () => {
    // The underlying locale map is built as {...en, ...lang}, so a key the
    // translator has not reached yet reads as English rather than undefined.
    // Verified through the view so a future refactor cannot lose that property.
    const zh = selectAuthCopy('zh-CN')
    for (const key of authCopyKeys) {
      expect(typeof zh[key]).toBe('string')
      expect(zh[key].length).toBeGreaterThan(0)
    }
  })

  it('is available in every supported language', () => {
    // Both apps render this component; a language that works in the calendar and
    // breaks in meet would be a difference between two mounts of one component.
    for (const lang of ['en', 'de', 'ja', 'zh-CN', 'fr', 'pt'] as const) {
      const copy = selectAuthCopy(lang)
      expect(copy.signIn.length).toBeGreaterThan(0)
      expect(copy.account.length).toBeGreaterThan(0)
    }
  })

  it('translates, rather than returning English for every language', () => {
    // A view that silently returned the English map would pass every test above.
    const en = selectAuthCopy('en')
    const de = selectAuthCopy('de')
    const differing = authCopyKeys.filter((k) => en[k] !== de[k])
    expect(differing.length).toBeGreaterThan(10)
  })
})
