import { promises as fs } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const projectRoot = path.resolve(__dirname, "..")
const localesDir = path.join(projectRoot, "locales")
const outputFile = path.join(projectRoot, "lib", "locales.ts")

const toIdentifier = (value) =>
  `locale${value.replace(/[^a-zA-Z0-9]+(.)/g, (_, chr) => chr.toUpperCase()).replace(/^[a-z]/, (chr) => chr.toUpperCase())}`

const run = async () => {
  const localeFiles = (await fs.readdir(localesDir))
    .filter((file) => file.endsWith(".json"))
    .sort((a, b) => a.localeCompare(b))

  if (localeFiles.length === 0) {
    throw new Error("No locale json files found in /locales")
  }

  const imports = localeFiles
    .map((file) => {
      const lang = file.replace(/\.json$/, "")
      const identifier = toIdentifier(lang)
      return `import ${identifier} from "@/locales/${file}"`
    })
    .join("\n")

  const entries = localeFiles
    .map((file) => {
      const lang = file.replace(/\.json$/, "")
      const identifier = toIdentifier(lang)
      return `  "${lang}": ${identifier},`
    })
    .join("\n")

  const content = `/* eslint-disable */\n// This file is auto-generated by lib/gen-locales.mjs\n// Do not edit manually.\n\n${imports}\n\nexport const translations = {\n${entries}\n} as const\n\nexport type Language = keyof typeof translations\n`

  await fs.writeFile(outputFile, content, "utf8")
  console.log(`Generated ${path.relative(projectRoot, outputFile)} with ${localeFiles.length} locale(s).`)
}

run().catch((error) => {
  console.error(error)
  process.exit(1)
})
