'use client'

import type { ComponentType, CSSProperties } from 'react'
import {
  Clock,
  AlarmClock,
  AlarmClockCheck,
  Anchor,
  Award,
  Baby,
  BadgeDollarSign,
  Bell,
  Bike,
  Bookmark,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Cake,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarHeart,
  Camera,
  Car,
  ChartLine,
  CircleCheck,
  ClipboardCheck,
  CloudRain,
  CloudSun,
  Code,
  Coffee,
  Coins,
  Compass,
  CreditCard,
  Crown,
  Dices,
  Dumbbell,
  Egg,
  FileText,
  Film,
  Flag,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  Ghost,
  Gift,
  Globe,
  GraduationCap,
  Guitar,
  Handshake,
  Heart,
  HeartHandshake,
  HeartPulse,
  History,
  Home,
  Hourglass,
  Info,
  Key,
  Laptop,
  Leaf,
  Lightbulb,
  Luggage,
  Map,
  MapPin,
  Medal,
  Mic,
  Moon,
  Mountain,
  Music,
  Notebook,
  Package,
  Palette,
  Palmtree,
  PartyPopper,
  PenLine,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Popcorn,
  Presentation,
  Puzzle,
  Rainbow,
  Receipt,
  Rocket,
  Shield,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Target,
  Tent,
  ThumbsUp,
  Ticket,
  Timer,
  Train,
  TramFront,
  TreePine,
  Trophy,
  Tv,
  Umbrella,
  Users,
  UtensilsCrossed,
  Wallet,
  Waves,
  Wine,
  Wrench,
  Zap,
} from 'lucide-react'

/** The props every catalogue glyph is rendered with. */
export interface CountdownGlyphProps {
  size?: number
  style?: CSSProperties
}

/**
 * The catalogue's glyphs, named explicitly.
 *
 * These three components used to reach for lucide the whole-library way —
 * `import * as` here and `import { icons }` in `countdown.tsx` — which no bundler can
 * tree-shake, so all ~6,300 icons became a static dependency of the calendar
 * chunk. Every other lucide import in this app is a named one.
 *
 * The list is generated from `@/lib/countdown-icons`, so it covers the catalogue
 * exactly. That doubles as the availability check the old `name in lucideIcons`
 * lookup provided: a name lucide has since renamed simply is not a key here, and
 * `countdown-icons.ts` filters on membership — a lucide rename now shows up as a
 * shorter list instead of a blank cell, which is what that filter was for.
 */
const GLYPHS: Record<string, ComponentType<CountdownGlyphProps>> = {
  Clock,
  AlarmClock,
  AlarmClockCheck,
  Anchor,
  Award,
  Baby,
  BadgeDollarSign,
  Bell,
  Bike,
  Bookmark,
  BookOpen,
  Briefcase,
  Building2,
  Bus,
  Cake,
  CalendarCheck,
  CalendarClock,
  CalendarDays,
  CalendarHeart,
  Camera,
  Car,
  ChartLine,
  CircleCheck,
  ClipboardCheck,
  CloudRain,
  CloudSun,
  Code,
  Coffee,
  Coins,
  Compass,
  CreditCard,
  Crown,
  Dices,
  Dumbbell,
  Egg,
  FileText,
  Film,
  Flag,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  Ghost,
  Gift,
  Globe,
  GraduationCap,
  Guitar,
  Handshake,
  Heart,
  HeartHandshake,
  HeartPulse,
  History,
  Home,
  Hourglass,
  Info,
  Key,
  Laptop,
  Leaf,
  Lightbulb,
  Luggage,
  Map,
  MapPin,
  Medal,
  Mic,
  Moon,
  Mountain,
  Music,
  Notebook,
  Package,
  Palette,
  Palmtree,
  PartyPopper,
  PenLine,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Popcorn,
  Presentation,
  Puzzle,
  Rainbow,
  Receipt,
  Rocket,
  Shield,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Snowflake,
  Sparkles,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Target,
  Tent,
  ThumbsUp,
  Ticket,
  Timer,
  Train,
  TramFront,
  TreePine,
  Trophy,
  Tv,
  Umbrella,
  Users,
  UtensilsCrossed,
  Wallet,
  Waves,
  Wine,
  Wrench,
  Zap,
}

/** True when a glyph exists for this catalogue name. */
export function hasCountdownGlyph(name: string): boolean {
  return Object.prototype.hasOwnProperty.call(GLYPHS, name)
}

/**
 * The glyph for a catalogue name, falling back to the Clock exactly as the
 * previous full-library lookup did — an unknown name renders a clock rather
 * than nothing.
 */
export function getCountdownGlyph(
  name: string,
): ComponentType<CountdownGlyphProps> {
  return GLYPHS[name] ?? GLYPHS.Clock
}
